<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'employee_number' => '100029267',
                'rfid_code' => '455051675',
                'first_name' => 'AERIEL',
                'middle_name' => 'C.',
                'last_name' => 'CABALLERO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100022649',
                'rfid_code' => '462242971',
                'first_name' => 'AIZA',
                'middle_name' => 'C.',
                'last_name' => 'CORTES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026074',
                'rfid_code' => '463346843',
                'first_name' => 'ANA LEAH',
                'middle_name' => 'D.',
                'last_name' => 'CUIZON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002521',
                'rfid_code' => '456940683',
                'first_name' => 'ANALY',
                'middle_name' => 'C.',
                'last_name' => 'BONGO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002504',
                'rfid_code' => '468450187',
                'first_name' => 'ANECITA',
                'middle_name' => 'T.',
                'last_name' => 'OMPAD',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002519',
                'rfid_code' => '455086747',
                'first_name' => 'ANNABELLE',
                'middle_name' => 'G.',
                'last_name' => 'MAGLASANG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027692',
                'rfid_code' => '459383707',
                'first_name' => 'ANNIE FE',
                'middle_name' => null,
                'last_name' => 'PEREZ-GALLARDO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002482',
                'rfid_code' => '454130827',
                'first_name' => 'APRIL ROSE',
                'middle_name' => 'A.',
                'last_name' => 'FALINCHAO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026082',
                'rfid_code' => '457805467',
                'first_name' => 'ARIEL RAYE',
                'middle_name' => 'V.',
                'last_name' => 'RICA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002483',
                'rfid_code' => '454309019',
                'first_name' => 'ARNELLA',
                'middle_name' => 'L.',
                'last_name' => 'LABISTE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002472',
                'rfid_code' => '453752475',
                'first_name' => 'AURELIO',
                'middle_name' => 'P.',
                'last_name' => 'VILBAR',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027560',
                'rfid_code' => '457573787',
                'first_name' => 'BAMBEE',
                'middle_name' => 'B.',
                'last_name' => 'MADRAZO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002386',
                'rfid_code' => '467381387',
                'first_name' => 'BELINDA',
                'middle_name' => 'F.',
                'last_name' => 'ESPIRITU',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100017201',
                'rfid_code' => '456430731',
                'first_name' => 'BELLY',
                'middle_name' => 'C.',
                'last_name' => 'SALINAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002421',
                'rfid_code' => '458432155',
                'first_name' => 'BRISNEVE',
                'middle_name' => null,
                'last_name' => 'EDULLANTES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100028113',
                'rfid_code' => '456921755',
                'first_name' => 'CATRINA',
                'middle_name' => null,
                'last_name' => 'ABELLA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100020279',
                'rfid_code' => '466463643',
                'first_name' => 'CECILIO',
                'middle_name' => 'M.',
                'last_name' => 'LABAJO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024194',
                'rfid_code' => '469306523',
                'first_name' => 'CHRISSA',
                'middle_name' => 'V.',
                'last_name' => 'SEVILLENO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021958',
                'rfid_code' => '463921547',
                'first_name' => 'CIPRIANO',
                'middle_name' => 'V.',
                'last_name' => 'OLITA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002507',
                'rfid_code' => '453535899',
                'first_name' => 'CORA JANE',
                'middle_name' => 'C.',
                'last_name' => 'LAWAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002432',
                'rfid_code' => '453378203',
                'first_name' => 'DEMELO',
                'middle_name' => 'M.',
                'last_name' => 'LAO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002389',
                'rfid_code' => '456304795',
                'first_name' => 'DENNIS',
                'middle_name' => 'E.',
                'last_name' => 'MONTERA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002546',
                'rfid_code' => '461464475',
                'first_name' => 'EDNA',
                'middle_name' => 'B.',
                'last_name' => 'DESUCATAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024989',
                'rfid_code' => '464878731',
                'first_name' => 'EDWIN',
                'middle_name' => 'B.',
                'last_name' => 'ESTRERA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002545',
                'rfid_code' => '466963867',
                'first_name' => 'EMMA',
                'middle_name' => 'O.',
                'last_name' => 'GANDIONCO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100028966',
                'rfid_code' => '455123867',
                'first_name' => 'ERICA LUNA',
                'middle_name' => null,
                'last_name' => 'ESCULTOR',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029166',
                'rfid_code' => '454381707',
                'first_name' => 'ERICKA MAE',
                'middle_name' => null,
                'last_name' => 'ENCABO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002522',
                'rfid_code' => '456034955',
                'first_name' => 'EUGENIE',
                'middle_name' => 'C.',
                'last_name' => 'BASTINEN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023017',
                'rfid_code' => '464385675',
                'first_name' => 'FERNAND',
                'middle_name' => 'G.',
                'last_name' => 'BERNARDEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002550',
                'rfid_code' => '455038107',
                'first_name' => 'FLOREDITH',
                'middle_name' => 'D.',
                'last_name' => 'SELERIO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002427',
                'rfid_code' => '462464923',
                'first_name' => 'FLORENCE',
                'middle_name' => 'C.',
                'last_name' => 'EVACITAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027833',
                'rfid_code' => '469144219',
                'first_name' => 'FRANCIS DOMINIQUE',
                'middle_name' => 'E.',
                'last_name' => 'FILIP',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002543',
                'rfid_code' => '467818395',
                'first_name' => 'FRANCIS LOUIE',
                'middle_name' => 'L.',
                'last_name' => 'ADAY',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026081',
                'rfid_code' => '463849115',
                'first_name' => 'FRANCIS REY',
                'middle_name' => 'U.',
                'last_name' => 'CORTES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023850',
                'rfid_code' => '461493899',
                'first_name' => 'GEMMA',
                'middle_name' => 'E.',
                'last_name' => 'JOGUILON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002479',
                'rfid_code' => '457717915',
                'first_name' => 'GEMMA',
                'middle_name' => 'M.',
                'last_name' => 'HERMOGENES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024093',
                'rfid_code' => '461362315',
                'first_name' => 'GENEVIEVE',
                'middle_name' => 'P.',
                'last_name' => 'PANTOLLANO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002542',
                'rfid_code' => '457342107',
                'first_name' => 'GERRAN',
                'middle_name' => 'H.',
                'last_name' => 'SIMACON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002503',
                'rfid_code' => '459317899',
                'first_name' => 'GODFREY',
                'middle_name' => 'B.',
                'last_name' => 'ESPAÑOL',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002529',
                'rfid_code' => '469543099',
                'first_name' => 'GRACE',
                'middle_name' => 'L.',
                'last_name' => 'MENDEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002471',
                'rfid_code' => '468146331',
                'first_name' => 'HAZEL',
                'middle_name' => 'A.',
                'last_name' => 'TRAPERO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026076',
                'rfid_code' => '466930059',
                'first_name' => 'IAN JAY',
                'middle_name' => 'A.',
                'last_name' => 'SERRA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024673',
                'rfid_code' => '455636891',
                'first_name' => 'INES',
                'middle_name' => 'S.',
                'last_name' => 'HISOLA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026075',
                'rfid_code' => '460691355',
                'first_name' => 'JACQUE BON-ISAAC',
                'middle_name' => 'C.',
                'last_name' => 'ABOY',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021979',
                'rfid_code' => '461616027',
                'first_name' => 'JAE MARI',
                'middle_name' => 'D.',
                'last_name' => 'MAGDADARO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023393',
                'rfid_code' => '461836443',
                'first_name' => 'JANICE',
                'middle_name' => 'V.',
                'last_name' => 'DIOLA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002476',
                'rfid_code' => '468495499',
                'first_name' => 'JANNETTE',
                'middle_name' => 'K.',
                'last_name' => 'LEPITEN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100025493',
                'rfid_code' => '465390747',
                'first_name' => 'JASELUH',
                'middle_name' => 'R.',
                'last_name' => 'SATURINAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023843',
                'rfid_code' => '457419675',
                'first_name' => 'JEAN',
                'middle_name' => 'P.',
                'last_name' => 'CENTINO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100025213',
                'rfid_code' => '462251403',
                'first_name' => 'JEFFREY',
                'middle_name' => 'D.',
                'last_name' => 'PELONIO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100010183',
                'rfid_code' => '469045659',
                'first_name' => 'JENETH',
                'middle_name' => 'B.',
                'last_name' => 'BORLASA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002459',
                'rfid_code' => '453472651',
                'first_name' => 'JERALINE',
                'middle_name' => 'E.',
                'last_name' => 'GUMALAL',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021978',
                'rfid_code' => '463640715',
                'first_name' => 'JERMYDEL',
                'middle_name' => 'T.',
                'last_name' => 'OMOLON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002501',
                'rfid_code' => '466108315',
                'first_name' => 'JESS',
                'middle_name' => 'J.',
                'last_name' => 'ZAPANTA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002403',
                'rfid_code' => '467639195',
                'first_name' => 'JESUS',
                'middle_name' => 'C.',
                'last_name' => 'CINCO',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027466',
                'rfid_code' => '467286171',
                'first_name' => 'JIMBOY',
                'middle_name' => 'R.',
                'last_name' => 'ALBARACIN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002455',
                'rfid_code' => '457618827',
                'first_name' => 'JOAN GRACE',
                'middle_name' => 'E.',
                'last_name' => 'PACRES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100022822',
                'rfid_code' => '456960139',
                'first_name' => 'JOHN JACQUES',
                'middle_name' => 'B.',
                'last_name' => 'SINAPUELAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100022781',
                'rfid_code' => '466970523',
                'first_name' => 'JOMALDEM',
                'middle_name' => 'B.',
                'last_name' => 'PANUGALING',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002454',
                'rfid_code' => '466899867',
                'first_name' => 'JONATHAN',
                'middle_name' => 'C.',
                'last_name' => 'DE LA CERNA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024992',
                'rfid_code' => '458850955',
                'first_name' => 'JOSEPH PATRICK',
                'middle_name' => 'T.',
                'last_name' => 'GUIEB',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002391',
                'rfid_code' => '464346267',
                'first_name' => 'JUANITO KARL',
                'middle_name' => 'P.',
                'last_name' => 'ROQUE',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100018196',
                'rfid_code' => '463781019',
                'first_name' => 'JUDITH',
                'middle_name' => 'M.',
                'last_name' => 'AGUANTA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100019279',
                'rfid_code' => '453327003',
                'first_name' => 'JULIE ANN',
                'middle_name' => 'L.',
                'last_name' => 'OREIRO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100028513',
                'rfid_code' => '465545099',
                'first_name' => 'JUN FRANCIS',
                'middle_name' => 'B.',
                'last_name' => 'MALDO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024095',
                'rfid_code' => '460884363',
                'first_name' => 'KARL KRIST',
                'middle_name' => null,
                'last_name' => 'NAVAJA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002450',
                'rfid_code' => '3502063899',
                'first_name' => 'Kim',
                'middle_name' => 'P.',
                'last_name' => 'Bondoc',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100010197',
                'rfid_code' => '461255835',
                'first_name' => 'LEAHLIZBETH',
                'middle_name' => 'A.',
                'last_name' => 'SIA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002478',
                'rfid_code' => '460521883',
                'first_name' => 'LILIA',
                'middle_name' => 'D.',
                'last_name' => 'SOCO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002495',
                'rfid_code' => '468285579',
                'first_name' => 'LOLITO',
                'middle_name' => 'T.',
                'last_name' => 'CANDELANZA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100025954',
                'rfid_code' => '455508619',
                'first_name' => 'LURY ED MARIE',
                'middle_name' => 'V.',
                'last_name' => 'YRAY',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002496',
                'rfid_code' => '456846731',
                'first_name' => 'LYNDON',
                'middle_name' => 'W.',
                'last_name' => 'LISONDRA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002463',
                'rfid_code' => '461820043',
                'first_name' => 'MA. ALENA',
                'middle_name' => 'N.',
                'last_name' => 'MACASIL',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026430',
                'rfid_code' => '457888139',
                'first_name' => 'MA. KRESNA',
                'middle_name' => 'N.',
                'last_name' => 'MANSUETO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024099',
                'rfid_code' => '458206363',
                'first_name' => 'MA. SALVACION',
                'middle_name' => 'B.',
                'last_name' => 'PANTINO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027562',
                'rfid_code' => '463651979',
                'first_name' => 'MAIKO',
                'middle_name' => 'P.',
                'last_name' => 'PALANG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002487',
                'rfid_code' => '465122459',
                'first_name' => 'MARIA THERESA',
                'middle_name' => 'P.',
                'last_name' => 'BARCENA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100015726',
                'rfid_code' => '463232155',
                'first_name' => 'MARICRIS',
                'middle_name' => 'C.',
                'last_name' => 'CAMANTANG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002540',
                'rfid_code' => '466831515',
                'first_name' => 'MARIE FE',
                'middle_name' => 'G.',
                'last_name' => 'LISONDRA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002516',
                'rfid_code' => '465784219',
                'first_name' => 'MARILOU',
                'middle_name' => 'B.',
                'last_name' => 'MANTE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002429',
                'rfid_code' => '454839707',
                'first_name' => 'MARY JOYCE',
                'middle_name' => 'L.',
                'last_name' => 'FLORES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002452',
                'rfid_code' => '460171147',
                'first_name' => 'MAY CHRISTINA',
                'middle_name' => 'G.',
                'last_name' => 'BUGASH',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024669',
                'rfid_code' => '459315339',
                'first_name' => 'MC NIÑO',
                'middle_name' => 'R.',
                'last_name' => 'VILLADORES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027468',
                'rfid_code' => '458580619',
                'first_name' => 'MICHAEL ANDREW',
                'middle_name' => 'S.',
                'last_name' => 'GALORIO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100017200',
                'rfid_code' => '455122315',
                'first_name' => 'MICHELLE',
                'middle_name' => 'J.',
                'last_name' => 'RODRIGUEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100017074',
                'rfid_code' => '460371611',
                'first_name' => 'NENNEN',
                'middle_name' => 'E.',
                'last_name' => 'ESCABILLAS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100022648',
                'rfid_code' => '3528505643',
                'first_name' => 'Noe John Joseph',
                'middle_name' => 'E.',
                'last_name' => 'Sacramento',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100010195',
                'rfid_code' => '456809611',
                'first_name' => 'NORREN',
                'middle_name' => 'C.',
                'last_name' => 'MERCADO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002396',
                'rfid_code' => '457990027',
                'first_name' => 'PALMY MARINEL',
                'middle_name' => 'P.',
                'last_name' => 'TUDTUD',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002437',
                'rfid_code' => '460300683',
                'first_name' => 'PATRICIA ANNE',
                'middle_name' => 'G.',
                'last_name' => 'NAZARENO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100018285',
                'rfid_code' => '458779803',
                'first_name' => 'PATRICIO',
                'middle_name' => 'B.',
                'last_name' => 'BALLOS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026083',
                'rfid_code' => '461876379',
                'first_name' => 'PERCIVAL',
                'middle_name' => 'J.',
                'last_name' => 'FORCADILLA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002468',
                'rfid_code' => '454449547',
                'first_name' => 'PHOEBE ZOE MARIA',
                'middle_name' => 'U.',
                'last_name' => 'SANCHE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029227',
                'rfid_code' => '464758683',
                'first_name' => 'PINKY JANE',
                'middle_name' => 'C.',
                'last_name' => 'PASCUAL',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002448',
                'rfid_code' => '463890587',
                'first_name' => 'PURITA',
                'middle_name' => 'T.',
                'last_name' => 'BALTAZAR',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002538',
                'rfid_code' => '459894427',
                'first_name' => 'RAFAEL',
                'middle_name' => 'T.',
                'last_name' => 'ABENASA',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024990',
                'rfid_code' => '453664155',
                'first_name' => 'RAMISES',
                'middle_name' => 'G.',
                'last_name' => 'MANZANO',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024991',
                'rfid_code' => '464741275',
                'first_name' => 'RAYMUND LEE ANTONIO',
                'middle_name' => 'C.',
                'last_name' => 'SAR',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021890',
                'rfid_code' => '459024283',
                'first_name' => 'RICKY',
                'middle_name' => 'R.',
                'last_name' => 'SALEM',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002484',
                'rfid_code' => '459645579',
                'first_name' => 'RITA',
                'middle_name' => 'C.',
                'last_name' => 'BINAGATAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002492',
                'rfid_code' => '457211291',
                'first_name' => 'RONALDO',
                'middle_name' => 'M.',
                'last_name' => 'BARGAMENTO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021841',
                'rfid_code' => '456044699',
                'first_name' => 'RUBELITO',
                'middle_name' => 'R.',
                'last_name' => 'ABELLA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100025388',
                'rfid_code' => '459373979',
                'first_name' => 'SEAN',
                'middle_name' => 'L.',
                'last_name' => 'POLICARPIO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002544',
                'rfid_code' => '469443227',
                'first_name' => 'SHERYL',
                'middle_name' => 'G.',
                'last_name' => 'ALFORQUE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027595',
                'rfid_code' => '462184075',
                'first_name' => 'SHEVEE',
                'middle_name' => 'V.',
                'last_name' => 'RESOLADO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100010201',
                'rfid_code' => '456759195',
                'first_name' => 'STEVENSON',
                'middle_name' => 'Q.',
                'last_name' => 'YU',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021811',
                'rfid_code' => '461077643',
                'first_name' => 'SUMMER',
                'middle_name' => 'M.',
                'last_name' => 'PLEÑOS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002506',
                'rfid_code' => '469462427',
                'first_name' => 'VENA',
                'middle_name' => 'D.',
                'last_name' => 'TOMAYAO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002480',
                'rfid_code' => '460299163',
                'first_name' => 'ZENAIDA',
                'middle_name' => 'L.',
                'last_name' => 'TABUCANON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029998',
                'rfid_code' => '453010059',
                'first_name' => 'ANDREA DANELLE',
                'middle_name' => 'P.',
                'last_name' => 'QUILANG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026487',
                'rfid_code' => '453954443',
                'first_name' => 'ARCHILL NIÑA',
                'middle_name' => 'F.',
                'last_name' => 'CAPISTRANO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029219',
                'rfid_code' => '467039131',
                'first_name' => 'CARINE ERA',
                'middle_name' => 'A.',
                'last_name' => 'LAPID',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029857',
                'rfid_code' => '458343819',
                'first_name' => 'DANNA BLAIR',
                'middle_name' => 'N.',
                'last_name' => 'BRIONES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100028615',
                'rfid_code' => '463270027',
                'first_name' => 'ELI EDRIAN',
                'middle_name' => 'L.',
                'last_name' => 'TAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100018143',
                'rfid_code' => '467312283',
                'first_name' => 'HAZEL',
                'middle_name' => 'O.',
                'last_name' => 'ARCEO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023895',
                'rfid_code' => '463657611',
                'first_name' => 'JASMIN',
                'middle_name' => null,
                'last_name' => 'SABELLINA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026567',
                'rfid_code' => '459635083',
                'first_name' => 'KAREN',
                'middle_name' => 'Y.',
                'last_name' => 'OCHEA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029997',
                'rfid_code' => '457147019',
                'first_name' => 'KYZYL ELNY',
                'middle_name' => 'N.',
                'last_name' => 'YAP',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002461',
                'rfid_code' => '457471115',
                'first_name' => 'MAGNOLIA',
                'middle_name' => 'A.',
                'last_name' => 'LAUS',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100031190',
                'rfid_code' => '453827211',
                'first_name' => 'MARY JOY',
                'middle_name' => 'A.',
                'last_name' => 'SAAVEDRA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024094',
                'rfid_code' => '468682907',
                'first_name' => 'NIÑO',
                'middle_name' => 'Y.',
                'last_name' => 'YBAÑEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002430',
                'rfid_code' => '455137931',
                'first_name' => 'RITCHELITA',
                'middle_name' => 'P.',
                'last_name' => 'GALAPATE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002502',
                'rfid_code' => '456410011',
                'first_name' => 'RODERIC',
                'middle_name' => 'O.',
                'last_name' => 'AGRAVANTE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002464',
                'rfid_code' => '468520091',
                'first_name' => 'ROWENA',
                'middle_name' => 'V.',
                'last_name' => 'MENDE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029992',
                'rfid_code' => '453116059',
                'first_name' => 'SRAM J ISLE',
                'middle_name' => 'L.',
                'last_name' => 'SANTILLAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002490',
                'rfid_code' => '4248055522',
                'first_name' => 'RONIE',
                'middle_name' => 'S.',
                'last_name' => 'BALILI',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002415',
                'rfid_code' => '4247344610',
                'first_name' => 'EUKENE',
                'middle_name' => 'O.',
                'last_name' => 'BENSIG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100032895',
                'rfid_code' => '4247133314',
                'first_name' => 'MARIE CRIS',
                'middle_name' => 'A.',
                'last_name' => 'BULAY-OG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035583',
                'rfid_code' => '4246767170',
                'first_name' => 'ROBE ANNE VELOSO',
                'middle_name' => null,
                'last_name' => 'DAYON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002426',
                'rfid_code' => '4246074066',
                'first_name' => 'NATIVIDAD VIRGINIA',
                'middle_name' => 'D.',
                'last_name' => 'ESTILLORE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034923',
                'rfid_code' => '4247351138',
                'first_name' => 'CLAIRE ANGELIE',
                'middle_name' => 'C.',
                'last_name' => 'GABISAY',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036187',
                'rfid_code' => '4245664690',
                'first_name' => 'PAOLA BIANCA',
                'middle_name' => 'F.',
                'last_name' => 'JAMOLIN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035757',
                'rfid_code' => '4245087714',
                'first_name' => 'FERDINAND',
                'middle_name' => null,
                'last_name' => 'VILLAHERMOSA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002399',
                'rfid_code' => '4247896338',
                'first_name' => 'JANUAR',
                'middle_name' => 'E.',
                'last_name' => 'YAP',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035759',
                'rfid_code' => '1047978050',
                'first_name' => 'DAISY',
                'middle_name' => 'A.',
                'last_name' => 'ROMEO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100033689',
                'rfid_code' => '1047092098',
                'first_name' => 'GABRIELA ISOBELLE NINA',
                'middle_name' => 'N.',
                'last_name' => 'VAÑO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024085',
                'rfid_code' => '1038592082',
                'first_name' => 'DEXTER',
                'middle_name' => 'G.',
                'last_name' => 'GABICA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002438',
                'rfid_code' => '1045585154',
                'first_name' => 'JASON',
                'middle_name' => 'A.',
                'last_name' => 'NIEVA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034841',
                'rfid_code' => '1045587538',
                'first_name' => 'JESSIE',
                'middle_name' => null,
                'last_name' => 'BRIONES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034947',
                'rfid_code' => '1038173042',
                'first_name' => 'JOHN KARL',
                'middle_name' => 'N.',
                'last_name' => 'CUIZON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036660',
                'rfid_code' => '1039272162',
                'first_name' => 'JOHN RYAN',
                'middle_name' => 'M.',
                'last_name' => 'JACOT',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036718',
                'rfid_code' => '1039298914',
                'first_name' => 'JOHN THOMAS',
                'middle_name' => null,
                'last_name' => 'TRINIDAD',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100025358',
                'rfid_code' => '1038620242',
                'first_name' => 'JONARESA',
                'middle_name' => 'M.',
                'last_name' => 'ARINAZA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002442',
                'rfid_code' => '1038500130',
                'first_name' => 'JUDITH',
                'middle_name' => 'R.',
                'last_name' => 'SILAPAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036691',
                'rfid_code' => '1038795858',
                'first_name' => 'KENNETH BERNEJAY',
                'middle_name' => 'H.',
                'last_name' => 'PORIO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036873',
                'rfid_code' => '1038497922',
                'first_name' => 'KIMBERLY KAYE',
                'middle_name' => 'A.',
                'last_name' => 'VARQUEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027746',
                'rfid_code' => '1038594226',
                'first_name' => 'LOUIE MICHAEL',
                'middle_name' => 'R.',
                'last_name' => 'LENARES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034949',
                'rfid_code' => '1045774258',
                'first_name' => 'NATHAN DAVE',
                'middle_name' => 'C.',
                'last_name' => 'LABRA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100010191',
                'rfid_code' => '1047316226',
                'first_name' => 'REGLETTO ALDRICH',
                'middle_name' => 'D.',
                'last_name' => 'IMBONG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026566',
                'rfid_code' => '1039225634',
                'first_name' => 'RICKY',
                'middle_name' => 'N.',
                'last_name' => 'LOGRONO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035862',
                'rfid_code' => '1039252658',
                'first_name' => 'ROSE CHINLY MAE',
                'middle_name' => 'O.',
                'last_name' => 'KINDICA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002384',
                'rfid_code' => '1045748946',
                'first_name' => 'SHANE',
                'middle_name' => 'L.',
                'last_name' => 'CARREON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100017061',
                'rfid_code' => '1047314306',
                'first_name' => 'SHERRY LYN',
                'middle_name' => 'G.',
                'last_name' => 'SAYCO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100016947',
                'rfid_code' => '2425496317',
                'first_name' => 'AILEEN JOAN',
                'middle_name' => 'O.',
                'last_name' => 'VICENTE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002493',
                'rfid_code' => '2425961197',
                'first_name' => 'ALBERT',
                'middle_name' => 'B.',
                'last_name' => 'BASCON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035755',
                'rfid_code' => '2428580077',
                'first_name' => 'ALEJANDRO',
                'middle_name' => 'A.',
                'last_name' => 'CABALLES',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035813',
                'rfid_code' => '2429526077',
                'first_name' => 'CHRISTYL JOHN',
                'middle_name' => 'M.',
                'last_name' => 'REPONTE',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100033824',
                'rfid_code' => '2428123405',
                'first_name' => 'CYRIL BRYAN',
                'middle_name' => 'D.',
                'last_name' => 'CUIZON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035299',
                'rfid_code' => '2427133677',
                'first_name' => 'DELIA',
                'middle_name' => 'D.',
                'last_name' => 'SIPULO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100033901',
                'rfid_code' => '2427858045',
                'first_name' => 'GRACE MARIE',
                'middle_name' => null,
                'last_name' => 'LOPEZ',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002388',
                'rfid_code' => '2425732637',
                'first_name' => 'GREGG',
                'middle_name' => 'S.',
                'last_name' => 'LLOREN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035784',
                'rfid_code' => '2426636701',
                'first_name' => 'JAVY PONCE',
                'middle_name' => null,
                'last_name' => 'MANAYON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034944',
                'rfid_code' => '2428037293',
                'first_name' => 'JAYNO',
                'middle_name' => 'M.',
                'last_name' => 'GERZON',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035783',
                'rfid_code' => '2429140061',
                'first_name' => 'JEREMAIAH',
                'middle_name' => 'L.',
                'last_name' => 'ESTRADA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100023029',
                'rfid_code' => '2425192733',
                'first_name' => 'JHORABEL',
                'middle_name' => 'O.',
                'last_name' => 'ALCANTARA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035781',
                'rfid_code' => '2428468301',
                'first_name' => 'KARL LYLE',
                'middle_name' => 'H.',
                'last_name' => 'NOEL',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100015727',
                'rfid_code' => '2425335837',
                'first_name' => 'KIM',
                'middle_name' => 'C.',
                'last_name' => 'KHO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100035295',
                'rfid_code' => '2426785965',
                'first_name' => 'MAIZEL',
                'middle_name' => 'N.',
                'last_name' => 'SAURA',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100033692',
                'rfid_code' => '2427909949',
                'first_name' => 'MARLEN',
                'middle_name' => 'D.',
                'last_name' => 'LIMPAG',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002500',
                'rfid_code' => '2426208637',
                'first_name' => 'NESTOR',
                'middle_name' => 'V.',
                'last_name' => 'TY',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034921',
                'rfid_code' => '2427048861',
                'first_name' => 'TRIZER DALE',
                'middle_name' => 'D.',
                'last_name' => 'MANSUETO',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100002462',
                'rfid_code' => '2427259309',
                'first_name' => 'ZENAIDA',
                'middle_name' => 'D.',
                'last_name' => 'LIGAN',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036871',
                'rfid_code' => '868796945',
                'first_name' => 'Adrian Francis',
                'middle_name' => 'G.',
                'last_name' => 'Carredo',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036480',
                'rfid_code' => '3504015227',
                'first_name' => 'Alvin',
                'middle_name' => 'G.',
                'last_name' => 'Roxas',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034950',
                'rfid_code' => '3501959291',
                'first_name' => 'Carl Milos',
                'middle_name' => 'R.',
                'last_name' => 'Bulilan',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100024994',
                'rfid_code' => '879052913',
                'first_name' => 'Ginessa',
                'middle_name' => 'M.',
                'last_name' => 'Rupinta',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036692',
                'rfid_code' => '892931457',
                'first_name' => 'Jonessa Faye',
                'middle_name' => 'E.',
                'last_name' => 'Abayon',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036788',
                'rfid_code' => '3525363611',
                'first_name' => 'Kriztel Nicole',
                'middle_name' => 'D.',
                'last_name' => 'Camalongay',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036693',
                'rfid_code' => '3501831739',
                'first_name' => 'Lionel Joseph',
                'middle_name' => 'T.',
                'last_name' => 'Sanchez',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100034759',
                'rfid_code' => '3504185243',
                'first_name' => 'Sofia Lee Jae',
                'middle_name' => 'E.',
                'last_name' => 'Yu',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036661',
                'rfid_code' => '3508420875',
                'first_name' => 'Vincent Crist',
                'middle_name' => 'S.',
                'last_name' => 'Lipayo',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100027909',
                'rfid_code' => '3508390011',
                'first_name' => 'Buenaventura',
                'middle_name' => 'M.',
                'last_name' => 'Ursaiz',
                'suffix' => 'JR',
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036745',
                'rfid_code' => '3505059611',
                'first_name' => 'Demie Xyza',
                'middle_name' => 'F.',
                'last_name' => 'Rendon',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036659',
                'rfid_code' => '868805249',
                'first_name' => 'Gelyn',
                'middle_name' => 'S.',
                'last_name' => 'Puracan',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036741',
                'rfid_code' => '888164113',
                'first_name' => 'Isabel Wen',
                'middle_name' => 'T.',
                'last_name' => 'Badon',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036740',
                'rfid_code' => '3526317179',
                'first_name' => 'Johnna Lyn',
                'middle_name' => 'S.',
                'last_name' => 'Amaya',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036713',
                'rfid_code' => '3530560187',
                'first_name' => 'Lucky Loreen',
                'middle_name' => 'S.',
                'last_name' => 'Legaspi',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036795',
                'rfid_code' => '3527300235',
                'first_name' => 'Allysa',
                'middle_name' => 'B.',
                'last_name' => 'Manatad',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100029994',
                'rfid_code' => '868898801',
                'first_name' => 'Dharyll Prince',
                'middle_name' => 'M.',
                'last_name' => 'Abellana',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036720',
                'rfid_code' => '888162881',
                'first_name' => 'Khriss Ihmmanuelle',
                'middle_name' => 'B.',
                'last_name' => 'Bajade',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100036658',
                'rfid_code' => '3528586811',
                'first_name' => 'Kobe Allen',
                'middle_name' => 'G.',
                'last_name' => 'Losenada',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100026072',
                'rfid_code' => '3504588251',
                'first_name' => 'Mileni',
                'middle_name' => 'L.',
                'last_name' => 'Torres',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
            [
                'employee_number' => '100021891',
                'rfid_code' => '3503731995',
                'first_name' => 'Noe',
                'middle_name' => 'M.',
                'last_name' => 'Santillan',
                'suffix' => null,
                'status' => 'Active Employee',
                'is_active' => true,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::updateOrCreate(
                ['employee_number' => $employee['employee_number']],
                $employee
            );
        }
    }
}
